modLoader="javafml"
loaderVersion="[40,)"
license="AGPL-3.0-only"
issueTrackerURL="https://github.com/Mimickal/MCDrops/issues"
[[mods]]
modId="mcdrops"
version="${file.jarVersion}"
displayName="Minecraft Drops"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
# TODO updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://github.com/Mimickal/MCDrops"
logoFile="mcdrops_logo.png"
credits="The Funbox crew for being my guinea pigs"
authors="Mimickal"
description="Periodically drop random items for active players"
